### ISSUE TITLE
I don't understand your README

### ISSUE THREAD

**Issue by dcosson** [pascalgrimaud/docker-ubuntu#1]
I'm having this issue on circleci too, but the commands in your Dockerfile file for me too with the error you mentioned.

Do you build this dockerfile on circleci? Or are you saying that you build it somewhere else first and then use it as the base image for projects that you build on circleci

**Comment by pascalgrimaud** [comment]
Hello Danny,
Currently, this Dockerfile can't be built on CircleCI, I hope CircleCI will fix it soon...
I use hub.docker to build it and, as you mentionned, use it as the base image for my other Dockerfiles.

I'll try to modify the README to be clear.

**Comment by dcosson** [comment]
Ok great, thanks for clarifying. Glad I wasn't the only one I thought I was going crazy :)

Never experienced this with docker before building & running with virtualbox & ec2, but multiple things break on CircleCI. Guess they're doing something weird + docker is not as isolated as I had thought :/
